version: '3.9'
services:
  blue:
    build: .
    image: ${BLUE_IMAGE}
    container_name: blue-app
    environment:
      - APP_COLOR=blue
      - APP_ENV=blue
      - APP_VERSION=${BLUE_VERSION}
    ports:
      - "3001:3000"
  green:
    build: .
    image: ${GREEN_IMAGE}
    container_name: green-app
    environment:
      - APP_COLOR=green
      - APP_ENV=green
      - APP_VERSION=${GREEN_VERSION}
    ports:
      - "3002:3000"
  proxy:
    image: nginx:1.27-alpine
    container_name: bluegreen-proxy
    depends_on:
      - blue
      - green
    environment:
      - ACTIVE_COLOR=${ACTIVE_COLOR}
    ports:
      - "8090:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    command: /bin/sh -c "envsubst '$$ACTIVE_COLOR' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
